# Specification for XpringKit's XCode project.
name: XpringKit
options:
  bundleIdPrefix: io.xpring
targets:
  XpringKit:
    type: framework
    platform: iOS
    sources: [XpringKit]
  XpringKitTests:
    type: bundle.unit-test
    platform: iOS
    sources: [Tests]
    dependencies:
      - target: XpringKit
