# Specification for XpringKit's XCode project.
name: XpringKit
options:
  bundleIdPrefix: io.xpring
targets:
  XpringKit:
    type: framework
    platform: iOS
    sources: [XpringKit]
    scheme:
      testTargets:
        - XpringKitTests
      gatherCoverageData: true
    preBuildScripts:
      - script: |
                mkdir -p ./XpringKit/generated
                protoc --proto_path=./terram-protos/models --proto_path=./terram-protos/services --swift_opt=Visibility=Public --swift_out=./XpringKit/generated --swiftgrpc_out=./XpringKit/generated ./terram-protos/*/*.proto
        name: Build Protos
    postCompileScripts:
      - script: swiftlint --config .swiftlint.yml
        name: SwiftLint
    dependencies:
      - carthage: SwiftProtobuf
      - carthage: SwiftGRPC
  XpringKitTests:
    type: bundle.unit-test
    platform: iOS
    sources: [Tests]
    dependencies:
      - target: XpringKit
