version: 2.1
jobs:
  build:
    macos:
      xcode: "10.2"

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Cartfile.resolved" }}

      - run:
          name: "Install Tooling"
          command: |
            export HOMEBREW_NO_AUTO_UPDATE=1
            brew install xcodegen swiftlint carthage swift-protobuf grpc-swift
            sudo gem install slather

      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote

      - run:
          name: "Build Dependencies"
          command: carthage update
          no_output_timeout: 30m

      - run:
          name: "Generate Protos"
          command: ./scripts/regenerate_protos.sh

      - run:
          name: "Generate Project"
          command: xcodegen generate

      - run:
          name: "Build and Test"
          command: set -o pipefail && xcodebuild test -scheme XpringKit -destination 'platform=iOS Simulator,name=iPhone X,OS=12.2' ONLY_ACTIVE_ARCH=YES | xcpretty

      - run:
          name: "Generate and Upload Code Coverage"
          command: slather

      - save_cache:
          paths:
            - Carthage
          key: v1-dependencies-{{ checksum "Cartfile.resolved" }}
