version: 2.1
orbs:
  protobuf: izumin5210/protobuf@0.1.0
jobs:
  build:
    macos:
      xcode: "10.2"

    steps:
      - checkout

      - protobuf/install

      - run:
          name: "Install Tooling"
          command: |
            brew install xcodegen swiftlint carthage swift-protobuf
            sudo gem install slather

      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote

      - run:
          name: "Build Dependencies"
          command: carthage update

      - run:
          name: "Generate Project"
          command: xcodegen generate

      - run:
          name: "Build and Test"
          command: set -o pipefail && xcodebuild test -scheme XpringKit -destination 'platform=iOS Simulator,name=iPhone X,OS=12.2' ONLY_ACTIVE_ARCH=YES | xcpretty

      - run:
          name: "Generate and Upload Code Coverage"
          command: slather
