version: 2.1
jobs:
  build:
    macos:
      xcode: "11.1.0"

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Cartfile.resolved" }}

      - run:
          name: "System Information"
          command: xcodebuild -version

      - run:
          name: "Install Tooling"
          command: |
            npm i -g grpc-tools
            brew install swift-protobuf grpc-swift

      - run:
          name: "Build and Test (CocoaPods)"
          command: pod lib lint --verbose
