version: 2.1
jobs:
  build:
    macos:
      xcode: "10.2"

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Cartfile.resolved" }}

      - run:
          name: "Install Tooling"
          command: |
            brew install xcodegen swiftlint carthage swift-protobuf grpc-swift node
            udo npm -g i grpc-tools
            sudo gem install slather

      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote

      - run:
          name: "Build Dependencies and Generate Project"
          command: ./scripts/generate_project.sh
          no_output_timeout: 30m

      - save_cache:
          paths:
            - Carthage
          key: v1-dependencies-{{ checksum "Cartfile.resolved" }}

      - run:
          name: "Build and Test"
          command: set -o pipefail && xcodebuild test -scheme XpringKit -destination 'platform=iOS Simulator,name=iPhone X,OS=12.2' ONLY_ACTIVE_ARCH=YES | xcpretty

      - run:
          name: "Generate and Upload Code Coverage"
          command: slather
