version: 2
jobs:
  build:
    macos:
      xcode: "10.3"

    steps:
      - checkout

      - run:
        name: "Generate Project"
        command: xcodegen generate

      - run:
        name: "Build and Test"
        command: |
          set -o pipefail && xcodebuild test -scheme XpringKit -derivedDataPath Build/ -destination 'platform=iOS Simulator,name=iPhone X,OS=12.4' ONLY_ACTIVE_ARCH=YES | xcpretty

      - run:
        name: "Generate Code Coverage"
        command: bundle exec slather

      - run:
        name: "Upload Code Coverage"
        command: "coveralls"
